<?php

use Illuminate\Database\Seeder;

class Ref_Aktiviti extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if(DB::table('ref__aktiviti')->get()->count() == 0){
            DB::table('ref__aktiviti')->insert([
                [ 'id' => 1, 'sub_bidang_id' => '1', 'aktiviti_description' => '3R KRT', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 2, 'sub_bidang_id' => '1', 'aktiviti_description' => 'Gotong Royong RT4All', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 3, 'sub_bidang_id' => '1', 'aktiviti_description' => 'Jom Kompos', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 4, 'sub_bidang_id' => '1', 'aktiviti_description' => 'Kejiranan Hijau', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 5, 'sub_bidang_id' => '1', 'aktiviti_description' => 'Kebun Komuniti', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 6, 'sub_bidang_id' => '1', 'aktiviti_description' => 'I-MAN', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 7, 'sub_bidang_id' => '1', 'aktiviti_description' => 'Program Rakan Alam Sekitar', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 8, 'sub_bidang_id' => '1', 'aktiviti_description' => 'Penilaian Pengurusan Sisa Pepejal dan Pembersihan Awam', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 9, 'sub_bidang_id' => '1', 'aktiviti_description' => 'Penilaian Pengurusan Lanskap', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 10, 'sub_bidang_id' => '2', 'aktiviti_description' => 'Mencegah dan menghalang penyakit berjangkit', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 11, 'sub_bidang_id' => '2', 'aktiviti_description' => 'Mencegah penyakit tidak berjangkit', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 12, 'sub_bidang_id' => '3', 'aktiviti_description' => 'Futsal', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 13, 'sub_bidang_id' => '3', 'aktiviti_description' => 'Midnight adventures', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 14, 'sub_bidang_id' => '3', 'aktiviti_description' => 'Sukan Perpaduan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 15, 'sub_bidang_id' => '3', 'aktiviti_description' => 'Kayuhan ceria', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 16, 'sub_bidang_id' => '3', 'aktiviti_description' => 'Liga perpaduan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 17, 'sub_bidang_id' => '3', 'aktiviti_description' => 'Larian perpaduan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 18, 'sub_bidang_id' => '3', 'aktiviti_description' => 'Unity e-sport', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 19, 'sub_bidang_id' => '3', 'aktiviti_description' => 'Merawai perpaduan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 20, 'sub_bidang_id' => '3', 'aktiviti_description' => 'Kembara perpaduan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 21, 'sub_bidang_id' => '4', 'aktiviti_description' => 'Penambahbaikan kemudahan asas', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 22, 'sub_bidang_id' => '4', 'aktiviti_description' => 'Pembinaan kemudahan asas', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 23, 'sub_bidang_id' => '5', 'aktiviti_description' => 'Pencegahan pelencongan sosial', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 24, 'sub_bidang_id' => '5', 'aktiviti_description' => 'Pencegahan pelencongan sosial', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 25, 'sub_bidang_id' => '6', 'aktiviti_description' => 'Program Kerohanian', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 26, 'sub_bidang_id' => '6', 'aktiviti_description' => 'Kelas mengaji', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 27, 'sub_bidang_id' => '7', 'aktiviti_description' => 'Program Kerohanian', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 28, 'sub_bidang_id' => '7', 'aktiviti_description' => 'Kelas mengaji', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 29, 'sub_bidang_id' => '8', 'aktiviti_description' => 'Program Kerohanian', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 30, 'sub_bidang_id' => '8', 'aktiviti_description' => 'Kelas mengaji', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 31, 'sub_bidang_id' => '9', 'aktiviti_description' => 'Program Kerohanian', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 32, 'sub_bidang_id' => '9', 'aktiviti_description' => 'Kelas mengaji', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 33, 'sub_bidang_id' => '10', 'aktiviti_description' => 'Program Kerohanian', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 34, 'sub_bidang_id' => '10', 'aktiviti_description' => 'Kelas mengaji', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 35, 'sub_bidang_id' => '11', 'aktiviti_description' => 'Program Kerohanian', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 36, 'sub_bidang_id' => '11', 'aktiviti_description' => 'Kelas mengaji', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 37, 'sub_bidang_id' => '12', 'aktiviti_description' => 'Program Kerohanian', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 38, 'sub_bidang_id' => '12', 'aktiviti_description' => 'Kelas mengaji', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 39, 'sub_bidang_id' => '13', 'aktiviti_description' => 'Program Kerohanian', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 40, 'sub_bidang_id' => '13', 'aktiviti_description' => 'Kelas mengaji', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 41, 'sub_bidang_id' => '14', 'aktiviti_description' => 'Program Kerohanian', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 42, 'sub_bidang_id' => '14', 'aktiviti_description' => 'Kelas mengaji', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 43, 'sub_bidang_id' => '15', 'aktiviti_description' => 'Skill2U', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 44, 'sub_bidang_id' => '15', 'aktiviti_description' => 'Projek Ekonomi Rukun Tetangga', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 45, 'sub_bidang_id' => '15', 'aktiviti_description' => 'e-Rezki', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 46, 'sub_bidang_id' => '15', 'aktiviti_description' => 'Program 1 Daerah 1 Produk (1D1P)', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 47, 'sub_bidang_id' => '15', 'aktiviti_description' => 'Program Pemasaran Atas Talian', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 48, 'sub_bidang_id' => '15', 'aktiviti_description' => 'Perantis Usahawan RT', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 49, 'sub_bidang_id' => '15', 'aktiviti_description' => 'Kebun Komuniti', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 50, 'sub_bidang_id' => '15', 'aktiviti_description' => 'Program Pengkomersilan Produk Komuniti Bersama Industri', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 51, 'sub_bidang_id' => '15', 'aktiviti_description' => 'Karnival Usahawan Muda', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 52, 'sub_bidang_id' => '15', 'aktiviti_description' => 'Program Usahawan Muda (My Preneur)', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 53, 'sub_bidang_id' => '15', 'aktiviti_description' => 'Car Boot Sale / Free Market Programme', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 54, 'sub_bidang_id' => '15', 'aktiviti_description' => 'Program Jejak Kerjaya', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 55, 'sub_bidang_id' => '15', 'aktiviti_description' => 'Program Keusahawanan Jiran Wanita', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 56, 'sub_bidang_id' => '16', 'aktiviti_description' => 'Jom Komuniti 3s', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 57, 'sub_bidang_id' => '16', 'aktiviti_description' => 'RT Cares (Ziarah Perpaduan)', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 58, 'sub_bidang_id' => '16', 'aktiviti_description' => 'RT Cares (Kotak Makanan/ Gerobok makanan)', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 59, 'sub_bidang_id' => '16', 'aktiviti_description' => 'RT2U : One Stop Community Centre', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 60, 'sub_bidang_id' => '16', 'aktiviti_description' => 'Info4Unity', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 61, 'sub_bidang_id' => '16', 'aktiviti_description' => 'Profil Komuniti', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 62, 'sub_bidang_id' => '16', 'aktiviti_description' => '#Youth4Unity', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 63, 'sub_bidang_id' => '16', 'aktiviti_description' => 'Kanta Selamat', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 64, 'sub_bidang_id' => '16', 'aktiviti_description' => 'Minggu Bersama Komuniti', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 65, 'sub_bidang_id' => '16', 'aktiviti_description' => 'Team Sukarelawan Muda', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 66, 'sub_bidang_id' => '16', 'aktiviti_description' => 'Kanta Komuniti', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 67, 'sub_bidang_id' => '16', 'aktiviti_description' => 'RT Mesra', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 68, 'sub_bidang_id' => '16', 'aktiviti_description' => 'Kenali RT', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 69, 'sub_bidang_id' => '16', 'aktiviti_description' => 'RT Cakna', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 70, 'sub_bidang_id' => '16', 'aktiviti_description' => 'Ikon/ influencer Komuniti', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 71, 'sub_bidang_id' => '16', 'aktiviti_description' => 'Mewujudkan Pasukan Kelompok Komuniti Peringkat Daerah/ Bahagian / Zon', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 72, 'sub_bidang_id' => '16', 'aktiviti_description' => 'Program Mesra Jiran', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 73, 'sub_bidang_id' => '16', 'aktiviti_description' => 'Pasukan Jiran Wanita Daerah', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 74, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Kursus Pengurusan dan Pentadbiran RT', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 75, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Kursus inventori permasalahan rakyat', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 76, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Kepimpinan Lestari', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 77, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Pengurusan Krisis dalam Kepimpinan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 78, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Mengarusperdanakan Gender', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 79, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Pemimpin Muda Lestari', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 80, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Pemimpin Muda Prihatin', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 81, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Young, Effective, Smart', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 82, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Pemikir Muda Inovatif dan Kreatift', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 83, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Program TUNAS', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 84, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Pembangunan Modul Program Setiap Kelompok', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 85, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Pembangunan Sudut Ilmu (mini Library)', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 86, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Kursus Kepimpinan Kelompok Komuniti', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 87, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Konvensyen Kelompok Komuniti Peringkat Kebangsaan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 88, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Program Cendekiawan Cilik (CELIK)', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 89, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Debat Remaja', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 90, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Program Akademi Pemimpin Muda', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 91, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Bengkel Latihan Kemahiran (TVET)', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 92, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Program Tuisyen Percuma', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 93, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Bengkel STEAM', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 94, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Pengurusan Kewangan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 95, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Hubungan etnik', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 96, 'sub_bidang_id' => '17', 'aktiviti_description' => 'Pelan Strategik', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 97, 'sub_bidang_id' => '18', 'aktiviti_description' => 'Projek Inovasi Jiran Muda', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 98, 'sub_bidang_id' => '18', 'aktiviti_description' => 'Internet of Thing (TOT)', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 99, 'sub_bidang_id' => '18', 'aktiviti_description' => 'Projek Inovasi Jiran Wanita', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 100, 'sub_bidang_id' => '18', 'aktiviti_description' => 'Projek Inovasi Rukun Tetangga', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 101, 'sub_bidang_id' => '19', 'aktiviti_description' => 'Sambutan Hari Guru', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 102, 'sub_bidang_id' => '19', 'aktiviti_description' => 'Bengkel Hujung Minggu Guru dan Pen. Guru', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 103, 'sub_bidang_id' => '19', 'aktiviti_description' => 'Program Pengukuhan dan Pemantapan KRN', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 104, 'sub_bidang_id' => '19', 'aktiviti_description' => 'Program My Rukun Negara', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 105, 'sub_bidang_id' => '19', 'aktiviti_description' => 'Program 1SRN 1 Komuniti', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 106, 'sub_bidang_id' => '19', 'aktiviti_description' => 'Bengkel Penasihat SRN', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 107, 'sub_bidang_id' => '19', 'aktiviti_description' => 'Program Pintar Kreatif', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 108, 'sub_bidang_id' => '19', 'aktiviti_description' => 'Hari Kecemerlangan Tabika dan Taska Perpaduan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 109, 'sub_bidang_id' => '19', 'aktiviti_description' => 'Program Tabika Perpaduan dan Taska Perpaduan bersama Rakan Perpaduan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 110, 'sub_bidang_id' => '19', 'aktiviti_description' => 'Program Latihan Industri Perpaduan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 111, 'sub_bidang_id' => '19', 'aktiviti_description' => 'Program Interaksi Industri Perpaduan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 112, 'sub_bidang_id' => '20', 'aktiviti_description' => 'Kempen Kibar Jalur Gemilang', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 113, 'sub_bidang_id' => '20', 'aktiviti_description' => 'Hari Kebangsaan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 114, 'sub_bidang_id' => '20', 'aktiviti_description' => 'Penghayatan Rukun Negara', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 115, 'sub_bidang_id' => '20', 'aktiviti_description' => 'Hari Malaysia', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 116, 'sub_bidang_id' => '20', 'aktiviti_description' => 'Debat Perpaduan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 117, 'sub_bidang_id' => '20', 'aktiviti_description' => 'Koir Patriotik', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 118, 'sub_bidang_id' => '20', 'aktiviti_description' => 'Program Detik-Detik Perpaduan', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 119, 'sub_bidang_id' => '21', 'aktiviti_description' => 'Sambutan Hari Toleransi', 'status'=> 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ]);
        }
    }
}
