<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RefDaerah extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // check if table users is empty
        if(DB::table('ref__daerahs')->get()->count() == 0){

            DB::table('ref__daerahs')->insert([
                ['id'=>1,'daerah_id'=>'0101','daerah_description'=>'BATU PAHAT','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>2,'daerah_id'=>'0102','daerah_description'=>'JOHOR BAHRU','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>3,'daerah_id'=>'0103','daerah_description'=>'KLUANG','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>4,'daerah_id'=>'0104','daerah_description'=>'KOTA TINGGI','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>5,'daerah_id'=>'0105','daerah_description'=>'MERSING','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>6,'daerah_id'=>'0106','daerah_description'=>'MUAR','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>7,'daerah_id'=>'0107','daerah_description'=>'PONTIAN','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>8,'daerah_id'=>'0108','daerah_description'=>'SEGAMAT','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>9,'daerah_id'=>'0109','daerah_description'=>'LEDANG','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>10,'daerah_id'=>'0110','daerah_description'=>'KULAIJAYA','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>11,'daerah_id'=>'0201','daerah_description'=>'BALING','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>12,'daerah_id'=>'0202','daerah_description'=>'BANDAR BAHRU','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>13,'daerah_id'=>'0203','daerah_description'=>'KOTA SETAR','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>14,'daerah_id'=>'0204','daerah_description'=>'KUALA MUDA','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>15,'daerah_id'=>'0205','daerah_description'=>'KUBANG PASU','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>16,'daerah_id'=>'0206','daerah_description'=>'KULIM','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>17,'daerah_id'=>'0207','daerah_description'=>'LANGKAWI','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>18,'daerah_id'=>'0208','daerah_description'=>'PADANG TERAP','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>19,'daerah_id'=>'0209','daerah_description'=>'SIK','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>21,'daerah_id'=>'0211','daerah_description'=>'PENDANG','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>22,'daerah_id'=>'0212','daerah_description'=>'POKOK SENA','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>23,'daerah_id'=>'0301','daerah_description'=>'BACHOK','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>24,'daerah_id'=>'0302','daerah_description'=>'KOTA BHARU','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>25,'daerah_id'=>'0303','daerah_description'=>'MACHANG','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>26,'daerah_id'=>'0304','daerah_description'=>'PASIR MAS','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>27,'daerah_id'=>'0305','daerah_description'=>'PASIR PUTEH','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>28,'daerah_id'=>'0306','daerah_description'=>'TANAH MERAH','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>29,'daerah_id'=>'0307','daerah_description'=>'TUMPAT','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>30,'daerah_id'=>'0308','daerah_description'=>'GUA MUSANG','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>31,'daerah_id'=>'0309','daerah_description'=>'KUALA KRAI','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>32,'daerah_id'=>'0310','daerah_description'=>'JELI','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>33,'daerah_id'=>'0311','daerah_description'=>'LOJING','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>34,'daerah_id'=>'0401','daerah_description'=>'ALOR GAJAH','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>35,'daerah_id'=>'0402','daerah_description'=>'JASIN','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>36,'daerah_id'=>'0403','daerah_description'=>'MELAKA TENGAH','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>37,'daerah_id'=>'0404','daerah_description'=>'MASJID TANAH','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>38,'daerah_id'=>'0501','daerah_description'=>'JELEBU','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>39,'daerah_id'=>'0502','daerah_description'=>'KUALA PILAH','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>40,'daerah_id'=>'0503','daerah_description'=>'PORT DICKSON','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>41,'daerah_id'=>'0504','daerah_description'=>'REMBAU','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>42,'daerah_id'=>'0505','daerah_description'=>'SEREMBAN','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>43,'daerah_id'=>'0506','daerah_description'=>'TAMPIN','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>44,'daerah_id'=>'0507','daerah_description'=>'JEMPOL','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>45,'daerah_id'=>'0508','daerah_description'=>'GEMAS','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>46,'daerah_id'=>'0601','daerah_description'=>'BENTONG','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>47,'daerah_id'=>'0602','daerah_description'=>'CAMERON HIGHLANDS','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>48,'daerah_id'=>'0603','daerah_description'=>'JERANTUT','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>49,'daerah_id'=>'0604','daerah_description'=>'KUANTAN','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>50,'daerah_id'=>'0605','daerah_description'=>'LIPIS','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>51,'daerah_id'=>'0606','daerah_description'=>'PEKAN','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>52,'daerah_id'=>'0607','daerah_description'=>'RAUB','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>53,'daerah_id'=>'0608','daerah_description'=>'TEMERLOH','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>54,'daerah_id'=>'0609','daerah_description'=>'ROMPIN','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>55,'daerah_id'=>'0610','daerah_description'=>'MARAN','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>56,'daerah_id'=>'0611','daerah_description'=>'BERA','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>57,'daerah_id'=>'0701','daerah_description'=>'SEBERANG PERAI TENGAH','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>58,'daerah_id'=>'0702','daerah_description'=>'SEBERANG PERAI UTARA','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>59,'daerah_id'=>'0703','daerah_description'=>'SEBERANG PERAI SELATAN','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>60,'daerah_id'=>'0704','daerah_description'=>'DAERAH TIMUR LAUT','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>61,'daerah_id'=>'0705','daerah_description'=>'DAERAH TIMUR DAYA','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>62,'daerah_id'=>'0801','daerah_description'=>'BATANG PADANG','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>63,'daerah_id'=>'0802','daerah_description'=>'MANJUNG','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>64,'daerah_id'=>'0803','daerah_description'=>'KINTA','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>65,'daerah_id'=>'0804','daerah_description'=>'KERIAN','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>66,'daerah_id'=>'0805','daerah_description'=>'KUALA KANGSAR','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>67,'daerah_id'=>'0806','daerah_description'=>'LARUT,MATANG & SELAMA','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>68,'daerah_id'=>'0807','daerah_description'=>'HILIR PERAK','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>69,'daerah_id'=>'0808','daerah_description'=>'HULU PERAK','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>70,'daerah_id'=>'0809','daerah_description'=>'PERAK TENGAH','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>71,'daerah_id'=>'0812','daerah_description'=>'KAMPAR','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>72,'daerah_id'=>'0813','daerah_description'=>'MUALLIM','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>73,'daerah_id'=>'0901','daerah_description'=>'PERLIS','state_id'=>'09','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>74,'daerah_id'=>'1001','daerah_description'=>'GOMBAK','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>75,'daerah_id'=>'1002','daerah_description'=>'KLANG','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>76,'daerah_id'=>'1003','daerah_description'=>'KUALA LANGAT','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>77,'daerah_id'=>'1004','daerah_description'=>'KUALA SELANGOR','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>78,'daerah_id'=>'1005','daerah_description'=>'PETALING','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>79,'daerah_id'=>'1006','daerah_description'=>'SABAK BERNAM','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>80,'daerah_id'=>'1007','daerah_description'=>'SEPANG','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>81,'daerah_id'=>'1008','daerah_description'=>'HULU LANGAT','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>82,'daerah_id'=>'1009','daerah_description'=>'HULU SELANGOR','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>83,'daerah_id'=>'1101','daerah_description'=>'BESUT','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>84,'daerah_id'=>'1102','daerah_description'=>'DUNGUN','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>85,'daerah_id'=>'1103','daerah_description'=>'KEMAMAN','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>86,'daerah_id'=>'1104','daerah_description'=>'MARANG','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>87,'daerah_id'=>'1105','daerah_description'=>'MARANG','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>88,'daerah_id'=>'1106','daerah_description'=>'HULU TERANGGANU','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>89,'daerah_id'=>'1107','daerah_description'=>'SETIU','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>90,'daerah_id'=>'1108','daerah_description'=>'KUALA NERUS','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>91,'daerah_id'=>'1201','daerah_description'=>'TAWAU','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>92,'daerah_id'=>'1202','daerah_description'=>'LAHAD DATU','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>93,'daerah_id'=>'1203','daerah_description'=>'SEMPORNA','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>94,'daerah_id'=>'1204','daerah_description'=>'SANDAKAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>95,'daerah_id'=>'1205','daerah_description'=>'KINABATANGAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>96,'daerah_id'=>'1206','daerah_description'=>'PUTATAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>97,'daerah_id'=>'1207','daerah_description'=>'KOTA KINABALU','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>98,'daerah_id'=>'1208','daerah_description'=>'RANAU','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>99,'daerah_id'=>'1209','daerah_description'=>'KUALA BELUD','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>100,'daerah_id'=>'1210','daerah_description'=>'TAMPARULI','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>101,'daerah_id'=>'1211','daerah_description'=>'PENAMPANG','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>102,'daerah_id'=>'1212','daerah_description'=>'PAPAR','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>103,'daerah_id'=>'1213','daerah_description'=>'KUDAT','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>104,'daerah_id'=>'1214','daerah_description'=>'KOTA MARUDU','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>105,'daerah_id'=>'1215','daerah_description'=>'PITAS','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>106,'daerah_id'=>'1216','daerah_description'=>'BEAUFORT','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>107,'daerah_id'=>'1217','daerah_description'=>'TUARAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>108,'daerah_id'=>'1218','daerah_description'=>'KENINGAU','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>109,'daerah_id'=>'1219','daerah_description'=>'BELURAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>110,'daerah_id'=>'1220','daerah_description'=>'TELUPID','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>111,'daerah_id'=>'1221','daerah_description'=>'KUALA PENYU','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>112,'daerah_id'=>'1222','daerah_description'=>'SIPITANG','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>113,'daerah_id'=>'1223','daerah_description'=>'MATUNGGONG','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>114,'daerah_id'=>'1224','daerah_description'=>'TENOM','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>115,'daerah_id'=>'1225','daerah_description'=>'TAMBUNAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>116,'daerah_id'=>'1226','daerah_description'=>'KUNAK','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>117,'daerah_id'=>'1227','daerah_description'=>'NABAWAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>118,'daerah_id'=>'1228','daerah_description'=>'KUNDASANG','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>119,'daerah_id'=>'1229','daerah_description'=>'MEMBAKUT','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>120,'daerah_id'=>'1230','daerah_description'=>'TONGOD','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>121,'daerah_id'=>'1301','daerah_description'=>'KUCHING','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>122,'daerah_id'=>'1302','daerah_description'=>'BAU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>123,'daerah_id'=>'1303','daerah_description'=>'SERIAN','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>124,'daerah_id'=>'1304','daerah_description'=>'SIMUNJAN','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>125,'daerah_id'=>'1305','daerah_description'=>'LUNDU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>126,'daerah_id'=>'1307','daerah_description'=>'LUBOK ANTU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>127,'daerah_id'=>'1310','daerah_description'=>'SIBU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>128,'daerah_id'=>'1311','daerah_description'=>'MUKAH','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>129,'daerah_id'=>'1312','daerah_description'=>'KANOWIT','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>130,'daerah_id'=>'1313','daerah_description'=>'DALAT','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>131,'daerah_id'=>'1314','daerah_description'=>'MIRI','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>132,'daerah_id'=>'1315','daerah_description'=>'BINTULU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>133,'daerah_id'=>'1316','daerah_description'=>'MATU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>134,'daerah_id'=>'1317','daerah_description'=>'LIMBANG','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>135,'daerah_id'=>'1318','daerah_description'=>'LAWAS','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>136,'daerah_id'=>'1319','daerah_description'=>'SARIKEI','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>137,'daerah_id'=>'1321','daerah_description'=>'DARO','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>138,'daerah_id'=>'1322','daerah_description'=>'JULAU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>139,'daerah_id'=>'1323','daerah_description'=>'KAPIT','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>140,'daerah_id'=>'1324','daerah_description'=>'SONG','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>141,'daerah_id'=>'1325','daerah_description'=>'BELAGA','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>142,'daerah_id'=>'1326','daerah_description'=>'SAMARAHAN','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>143,'daerah_id'=>'1327','daerah_description'=>'MERADONG','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>144,'daerah_id'=>'1328','daerah_description'=>'SRI AMAN','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>145,'daerah_id'=>'1387','daerah_description'=>'SELANGAU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>146,'daerah_id'=>'1390','daerah_description'=>'BETONG','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>147,'daerah_id'=>'1391','daerah_description'=>'PAKAN','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>148,'daerah_id'=>'1392','daerah_description'=>'TATAU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>149,'daerah_id'=>'1393','daerah_description'=>'MARUDI','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>150,'daerah_id'=>'1394','daerah_description'=>'SARATOK','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>151,'daerah_id'=>'1395','daerah_description'=>'ASAJAYA','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>152,'daerah_id'=>'1402','daerah_description'=>'BRICKFIELDS','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>153,'daerah_id'=>'1403','daerah_description'=>'DANG WANGI','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>154,'daerah_id'=>'1404','daerah_description'=>'CHERAS','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>155,'daerah_id'=>'1405','daerah_description'=>'SENTUL','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>156,'daerah_id'=>'1501','daerah_description'=>'LABUAN','state_id'=>'15','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>157,'daerah_id'=>'1601','daerah_description'=>'PUTRAJAYA','state_id'=>'16','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>158,'daerah_id'=>'1231','daerah_description'=>'SOOK','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>159,'daerah_id'=>'9901','daerah_description'=>'UMUM','state_id'=>'99','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ]);

        }
    }
}
