<?php

use Illuminate\Database\Seeder;

class RefKaum extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // check if table users is empty
        if(DB::table('ref__kaum')->get()->count() == 0){
            DB::table('ref__kaum')->insert([
                [ 'id' => 1, 'kod_kaum' => '01', 'kaum_description' => 'MELAYU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 2, 'kod_kaum' => '02', 'kaum_description' => 'BUGIS', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 3, 'kod_kaum' => '03', 'kaum_description' => 'BOYAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 4, 'kod_kaum' => '04', 'kaum_description' => 'BANJAR', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 5, 'kod_kaum' => '05', 'kaum_description' => 'JAWA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 6, 'kod_kaum' => '06', 'kaum_description' => 'JAWI PEKAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 7, 'kod_kaum' => '07', 'kaum_description' => 'MINANGKABAU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 8, 'kod_kaum' => '08', 'kaum_description' => 'CINA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 9, 'kod_kaum' => '09', 'kaum_description' => 'CANTONESE', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 10, 'kod_kaum' => '10', 'kaum_description' => 'FOOCHOW', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 11, 'kod_kaum' => '11', 'kaum_description' => 'HAINANESE', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 12, 'kod_kaum' => '12', 'kaum_description' => 'HENGHUA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 13, 'kod_kaum' => '13', 'kaum_description' => 'HOKCHIA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 14, 'kod_kaum' => '14', 'kaum_description' => 'HOKCHIU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 15, 'kod_kaum' => '15', 'kaum_description' => 'HOKKIEN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 16, 'kod_kaum' => '16', 'kaum_description' => 'KHEK (HAKKA)', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 17, 'kod_kaum' => '17', 'kaum_description' => 'KWONGSAI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 18, 'kod_kaum' => '18', 'kaum_description' => 'TEOCHEW', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 19, 'kod_kaum' => '19', 'kaum_description' => 'KONGFOO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 20, 'kod_kaum' => '20', 'kaum_description' => 'HYLAM', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 21, 'kod_kaum' => '21', 'kaum_description' => 'INDIA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 22, 'kod_kaum' => '22', 'kaum_description' => 'MALAYALI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 23, 'kod_kaum' => '23', 'kaum_description' => 'PUNJABI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 24, 'kod_kaum' => '24', 'kaum_description' => 'SIKH', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 25, 'kod_kaum' => '25', 'kaum_description' => 'TAMIL', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 26, 'kod_kaum' => '26', 'kaum_description' => 'TELEGU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 27, 'kod_kaum' => '27', 'kaum_description' => 'MALABARI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 28, 'kod_kaum' => '28', 'kaum_description' => 'INDIA MUSLIM', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 29, 'kod_kaum' => '29', 'kaum_description' => 'TELUGU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 30, 'kod_kaum' => '30', 'kaum_description' => 'ORISSA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 31, 'kod_kaum' => '31', 'kaum_description' => 'BANGLADESHI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 32, 'kod_kaum' => '32', 'kaum_description' => 'PAKISTANI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 33, 'kod_kaum' => '33', 'kaum_description' => 'SRI LANKA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 34, 'kod_kaum' => '34', 'kaum_description' => 'TAMIL SRI LANKA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 35, 'kod_kaum' => '35', 'kaum_description' => 'MELAYU SRI LANKA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 36, 'kod_kaum' => '36', 'kaum_description' => 'SINHALESE', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 37, 'kod_kaum' => '37', 'kaum_description' => 'CEYLONESE', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 38, 'kod_kaum' => '38', 'kaum_description' => 'INDONESIA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 39, 'kod_kaum' => '39', 'kaum_description' => 'TIDUNG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 40, 'kod_kaum' => '40', 'kaum_description' => 'ETNIK SABAH', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 41, 'kod_kaum' => '41', 'kaum_description' => 'BAJAU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 42, 'kod_kaum' => '42', 'kaum_description' => 'DUSUN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 43, 'kod_kaum' => '43', 'kaum_description' => 'KADAZAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 44, 'kod_kaum' => '44', 'kaum_description' => 'MURUT', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 45, 'kod_kaum' => '45', 'kaum_description' => 'SINO-NATIVE', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 46, 'kod_kaum' => '46', 'kaum_description' => 'SULUK', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 47, 'kod_kaum' => '47', 'kaum_description' => 'TIDUNG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 48, 'kod_kaum' => '48', 'kaum_description' => 'BINADAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 49, 'kod_kaum' => '49', 'kaum_description' => 'BISAYA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 50, 'kod_kaum' => '50', 'kaum_description' => 'BONGOL', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 51, 'kod_kaum' => '51', 'kaum_description' => 'BRUNEI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 52, 'kod_kaum' => '52', 'kaum_description' => 'DUMPAS', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 53, 'kod_kaum' => '53', 'kaum_description' => 'IRANUN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 54, 'kod_kaum' => '54', 'kaum_description' => 'IDAHAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 55, 'kod_kaum' => '55', 'kaum_description' => 'KWIJAU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 56, 'kod_kaum' => '56', 'kaum_description' => 'KEDAYAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 57, 'kod_kaum' => '57', 'kaum_description' => 'LINGKABAU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 58, 'kod_kaum' => '58', 'kaum_description' => 'LUNDAYEH', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 59, 'kod_kaum' => '59', 'kaum_description' => 'LASAU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 60, 'kod_kaum' => '60', 'kaum_description' => 'MELANAU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 61, 'kod_kaum' => '61', 'kaum_description' => 'MANGKAAK', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 62, 'kod_kaum' => '62', 'kaum_description' => 'MATAGANG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 63, 'kod_kaum' => '63', 'kaum_description' => 'MINOKOK', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 64, 'kod_kaum' => '64', 'kaum_description' => 'MELAYU SABAH', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 65, 'kod_kaum' => '65', 'kaum_description' => 'MOMOGUN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 66, 'kod_kaum' => '66', 'kaum_description' => 'PAITAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 67, 'kod_kaum' => '67', 'kaum_description' => 'RUMANAU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 68, 'kod_kaum' => '68', 'kaum_description' => 'RUNGUS', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 69, 'kod_kaum' => '69', 'kaum_description' => 'SUNGAI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 70, 'kod_kaum' => '70', 'kaum_description' => 'SONSONGAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 71, 'kod_kaum' => '71', 'kaum_description' => 'SINULIHAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 72, 'kod_kaum' => '72', 'kaum_description' => 'TOMBONUO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 73, 'kod_kaum' => '73', 'kaum_description' => 'TAGAL', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 74, 'kod_kaum' => '74', 'kaum_description' => 'TINAGAS', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 75, 'kod_kaum' => '75', 'kaum_description' => 'COCOS', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 76, 'kod_kaum' => '76', 'kaum_description' => 'KIMARAGANG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 77, 'kod_kaum' => '77', 'kaum_description' => 'BOLONGAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 78, 'kod_kaum' => '78', 'kaum_description' => 'BUTON', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 79, 'kod_kaum' => '79', 'kaum_description' => 'KAGAYAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 80, 'kod_kaum' => '80', 'kaum_description' => 'BALABAK', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 81, 'kod_kaum' => '81', 'kaum_description' => 'KADAZAN-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 82, 'kod_kaum' => '82', 'kaum_description' => 'DUSUN-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 83, 'kod_kaum' => '83', 'kaum_description' => 'BAJAU-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 84, 'kod_kaum' => '84', 'kaum_description' => 'MURUT-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 85, 'kod_kaum' => '85', 'kaum_description' => 'BRUNEI-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 86, 'kod_kaum' => '86', 'kaum_description' => 'RUNGUS-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 87, 'kod_kaum' => '87', 'kaum_description' => 'BISAYA-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 88, 'kod_kaum' => '88', 'kaum_description' => 'IDAHAN-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 89, 'kod_kaum' => '89', 'kaum_description' => 'IRANUN-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 90, 'kod_kaum' => '90', 'kaum_description' => 'KEDAYAN-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 91, 'kod_kaum' => '91', 'kaum_description' => 'SUNGAI-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 92, 'kod_kaum' => '92', 'kaum_description' => 'LUNDAYEH-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 93, 'kod_kaum' => '93', 'kaum_description' => 'SULUK-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 94, 'kod_kaum' => '94', 'kaum_description' => 'TIDUNG-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 95, 'kod_kaum' => '95', 'kaum_description' => 'BOLONGAN-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 96, 'kod_kaum' => '96', 'kaum_description' => 'BALABAK-SINO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 97, 'kod_kaum' => '97', 'kaum_description' => 'BUMIPUTERA SARAWAK', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 98, 'kod_kaum' => '98', 'kaum_description' => 'MELAYU SARAWAK', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 99, 'kod_kaum' => '99', 'kaum_description' => 'MELANAU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 100, 'kod_kaum' => '100', 'kaum_description' => 'KEDAYAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 101, 'kod_kaum' => '101', 'kaum_description' => 'IBAN ATAU SEA DAYAK', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 102, 'kod_kaum' => '102', 'kaum_description' => 'BIDAYUH ATAU LAND DAYAK', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 103, 'kod_kaum' => '103', 'kaum_description' => 'KAYAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 104, 'kod_kaum' => '104', 'kaum_description' => 'KENYAH', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 105, 'kod_kaum' => '105', 'kaum_description' => 'MURUT ATAU LUN BAWANG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 106, 'kod_kaum' => '106', 'kaum_description' => 'KELABIT', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 107, 'kod_kaum' => '107', 'kaum_description' => 'PUNAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 108, 'kod_kaum' => '108', 'kaum_description' => 'PENAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 109, 'kod_kaum' => '109', 'kaum_description' => 'BISAYA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 110, 'kod_kaum' => '110', 'kaum_description' => 'BERAWAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 111, 'kod_kaum' => '111', 'kaum_description' => 'BELOT', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 112, 'kod_kaum' => '112', 'kaum_description' => 'BUKET', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 113, 'kod_kaum' => '113', 'kaum_description' => 'BALAU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 114, 'kod_kaum' => '114', 'kaum_description' => 'BATANG AI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 115, 'kod_kaum' => '115', 'kaum_description' => 'BATU ELAH', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 116, 'kod_kaum' => '116', 'kaum_description' => 'BAKETAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 117, 'kod_kaum' => '117', 'kaum_description' => 'BINTULU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 118, 'kod_kaum' => '118', 'kaum_description' => 'BADANG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 119, 'kod_kaum' => '119', 'kaum_description' => 'DUSUN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 120, 'kod_kaum' => '120', 'kaum_description' => 'JAGOI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 121, 'kod_kaum' => '121', 'kaum_description' => 'LAKIPUT', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 122, 'kod_kaum' => '122', 'kaum_description' => 'KAJANG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 123, 'kod_kaum' => '123', 'kaum_description' => 'KEJAMAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 124, 'kod_kaum' => '124', 'kaum_description' => 'KANOWIT', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 125, 'kod_kaum' => '125', 'kaum_description' => 'LIRONG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 126, 'kod_kaum' => '126', 'kaum_description' => 'LEMANAK', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 127, 'kod_kaum' => '127', 'kaum_description' => 'LAHANAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 128, 'kod_kaum' => '128', 'kaum_description' => 'LISUM ATAU LUGUM', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 129, 'kod_kaum' => '129', 'kaum_description' => 'MATU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 130, 'kod_kaum' => '130', 'kaum_description' => 'MEMALOH', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 131, 'kod_kaum' => '131', 'kaum_description' => 'MELIKIN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 132, 'kod_kaum' => '132', 'kaum_description' => 'MELAING', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 133, 'kod_kaum' => '133', 'kaum_description' => 'NGURIK', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 134, 'kod_kaum' => '134', 'kaum_description' => 'MENONDO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 135, 'kod_kaum' => '135', 'kaum_description' => 'NYAMOK', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 136, 'kod_kaum' => '136', 'kaum_description' => 'SEBOP', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 137, 'kod_kaum' => '137', 'kaum_description' => 'SEDUAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 138, 'kod_kaum' => '138', 'kaum_description' => 'SEKAPAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 139, 'kod_kaum' => '139', 'kaum_description' => 'SEGALANG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 140, 'kod_kaum' => '140', 'kaum_description' => 'SIHAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 141, 'kod_kaum' => '141', 'kaum_description' => 'SIPENG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 142, 'kod_kaum' => '142', 'kaum_description' => 'SARIBAS', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 143, 'kod_kaum' => '143', 'kaum_description' => 'SEBUYAU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 144, 'kod_kaum' => '144', 'kaum_description' => 'SKRANG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 145, 'kod_kaum' => '145', 'kaum_description' => 'SABAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 146, 'kod_kaum' => '146', 'kaum_description' => 'SELAKAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 147, 'kod_kaum' => '147', 'kaum_description' => 'SELAKO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 148, 'kod_kaum' => '148', 'kaum_description' => 'TAGAL', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 149, 'kod_kaum' => '149', 'kaum_description' => 'TABUN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 150, 'kod_kaum' => '150', 'kaum_description' => 'TUTONG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 151, 'kod_kaum' => '151', 'kaum_description' => 'TANJONG', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 152, 'kod_kaum' => '152', 'kaum_description' => 'TATAU', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 153, 'kod_kaum' => '153', 'kaum_description' => 'TAUP', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 154, 'kod_kaum' => '154', 'kaum_description' => 'UKIT', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 155, 'kod_kaum' => '155', 'kaum_description' => 'UNKOP', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 156, 'kod_kaum' => '156', 'kaum_description' => 'ULU AI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 157, 'kod_kaum' => '157', 'kaum_description' => 'TORAJA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 158, 'kod_kaum' => '158', 'kaum_description' => 'TIMOR', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 159, 'kod_kaum' => '159', 'kaum_description' => 'MENADO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 160, 'kod_kaum' => '160', 'kaum_description' => 'MANURA', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 161, 'kod_kaum' => '161', 'kaum_description' => 'BATAK', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 162, 'kod_kaum' => '162', 'kaum_description' => 'PATHAN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 163, 'kod_kaum' => '163', 'kaum_description' => 'TONGANS', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 164, 'kod_kaum' => '164', 'kaum_description' => 'ORANG ASLI (SEMENANJUNG)', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 165, 'kod_kaum' => '165', 'kaum_description' => 'JAKUN', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 166, 'kod_kaum' => '166', 'kaum_description' => 'NEGRITO', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 167, 'kod_kaum' => '167', 'kaum_description' => 'SAKAI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 168, 'kod_kaum' => '168', 'kaum_description' => 'SEMAI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 169, 'kod_kaum' => '169', 'kaum_description' => 'SEMALAI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 170, 'kod_kaum' => '170', 'kaum_description' => 'TEMIAR', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                [ 'id' => 171, 'kod_kaum' => '171', 'kaum_description' => 'SENOI', 'status'=>1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')]
            ]);
        }
    }
}