<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RefParlimen extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // check if table is empty
        if(DB::table('ref__parlimens')->get()->count() == 0){

            DB::table('ref__parlimens')->insert([
                ['id'=>1, 'parlimen_id'=>'001','parlimen_description'=>'PADANG BESAR','state_id'=>'09','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>2, 'parlimen_id'=>'002','parlimen_description'=>'KANGAR','state_id'=>'09','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>3, 'parlimen_id'=>'003','parlimen_description'=>'ARAU','state_id'=>'09','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>4, 'parlimen_id'=>'004','parlimen_description'=>'LANGKAWI','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>5, 'parlimen_id'=>'005','parlimen_description'=>'JERLUN','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>6, 'parlimen_id'=>'006','parlimen_description'=>'KUBANG PASU','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>7, 'parlimen_id'=>'007','parlimen_description'=>'PADANG TERAP','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>8, 'parlimen_id'=>'008','parlimen_description'=>'POKOK SENA','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>9, 'parlimen_id'=>'009','parlimen_description'=>'ALOR SETAR','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>10, 'parlimen_id'=>'010','parlimen_description'=>'KUALA KEDAH','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>11, 'parlimen_id'=>'011','parlimen_description'=>'PENDANG','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>12, 'parlimen_id'=>'012','parlimen_description'=>'JERAI','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>13, 'parlimen_id'=>'013','parlimen_description'=>'SIK','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>14, 'parlimen_id'=>'014','parlimen_description'=>'MERBOK','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>15, 'parlimen_id'=>'015','parlimen_description'=>'SUNGAI PETANI','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>16, 'parlimen_id'=>'016','parlimen_description'=>'BALING','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>17, 'parlimen_id'=>'017','parlimen_description'=>'PADANG SERAI','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>18, 'parlimen_id'=>'018','parlimen_description'=>'KULIM-BANDAR BAHARU','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>19, 'parlimen_id'=>'019','parlimen_description'=>'TUMPAT','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>20, 'parlimen_id'=>'020','parlimen_description'=>'PENGKALAN CHEPA','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>21, 'parlimen_id'=>'021','parlimen_description'=>'KOTA BHARU','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>22, 'parlimen_id'=>'022','parlimen_description'=>'PASIR MAS','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>23, 'parlimen_id'=>'023','parlimen_description'=>'RANTAU PANJANG','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>24, 'parlimen_id'=>'024','parlimen_description'=>'KUBANG KERIAN','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>25, 'parlimen_id'=>'025','parlimen_description'=>'BACHOK','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>26, 'parlimen_id'=>'026','parlimen_description'=>'KETEREH','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>27, 'parlimen_id'=>'027','parlimen_description'=>'TANAH MERAH','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>28, 'parlimen_id'=>'028','parlimen_description'=>'PASIR PUTEH','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>29, 'parlimen_id'=>'029','parlimen_description'=>'MACHANG','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>30, 'parlimen_id'=>'030','parlimen_description'=>'JELI','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>31, 'parlimen_id'=>'031','parlimen_description'=>'KUALA KRAI','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>32, 'parlimen_id'=>'032','parlimen_description'=>'GUA MUSANG','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>33, 'parlimen_id'=>'033','parlimen_description'=>'BESUT','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>34, 'parlimen_id'=>'034','parlimen_description'=>'SETIU','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>35, 'parlimen_id'=>'035','parlimen_description'=>'KUALA NERUS','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>36, 'parlimen_id'=>'036','parlimen_description'=>'KUALA TERENGGANU','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>37, 'parlimen_id'=>'037','parlimen_description'=>'MARANG','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>38, 'parlimen_id'=>'038','parlimen_description'=>'HULU TERENGGANU','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>39, 'parlimen_id'=>'039','parlimen_description'=>'DUNGUN','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>40, 'parlimen_id'=>'040','parlimen_description'=>'KEMAMAN','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>41, 'parlimen_id'=>'041','parlimen_description'=>'KEPALA BATAS','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>42, 'parlimen_id'=>'042','parlimen_description'=>'TASEK GELUGOR','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>43, 'parlimen_id'=>'043','parlimen_description'=>'BAGAN','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>44, 'parlimen_id'=>'044','parlimen_description'=>'PERMATANG PAUH','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>45, 'parlimen_id'=>'045','parlimen_description'=>'BUKIT MERTAJAM','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>46, 'parlimen_id'=>'046','parlimen_description'=>'BATU KAWAN','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>47, 'parlimen_id'=>'047','parlimen_description'=>'NIBONG TEBAL','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>48, 'parlimen_id'=>'048','parlimen_description'=>'BUKIT BENDERA','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>49, 'parlimen_id'=>'049','parlimen_description'=>'TANJONG','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>50, 'parlimen_id'=>'050','parlimen_description'=>'JELUTONG','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>51, 'parlimen_id'=>'051','parlimen_description'=>'BUKIT GELUGOR','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>52, 'parlimen_id'=>'052','parlimen_description'=>'BAYAN BARU','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>53, 'parlimen_id'=>'053','parlimen_description'=>'BALIK PULAU','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>54, 'parlimen_id'=>'054','parlimen_description'=>'GERIK','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>55, 'parlimen_id'=>'055','parlimen_description'=>'LENGGONG','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>56, 'parlimen_id'=>'056','parlimen_description'=>'LARUT','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>57, 'parlimen_id'=>'057','parlimen_description'=>'PARIT BUNTAR','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>58, 'parlimen_id'=>'058','parlimen_description'=>'BAGAN SERAI','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>59, 'parlimen_id'=>'059','parlimen_description'=>'BUKIT GANTANG','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>60, 'parlimen_id'=>'060','parlimen_description'=>'TAIPING','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>61, 'parlimen_id'=>'061','parlimen_description'=>'PADANG RENGAS','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>62, 'parlimen_id'=>'062','parlimen_description'=>'SUNGAI SIPUT','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>63, 'parlimen_id'=>'063','parlimen_description'=>'TAMBUN','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>64, 'parlimen_id'=>'064','parlimen_description'=>'IPOH TIMOR','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>65, 'parlimen_id'=>'065','parlimen_description'=>'IPOH BARAT','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>66, 'parlimen_id'=>'066','parlimen_description'=>'BATU GAJAH','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>67, 'parlimen_id'=>'067','parlimen_description'=>'KUALA KANGSAR','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>68, 'parlimen_id'=>'068','parlimen_description'=>'BERUAS','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>69, 'parlimen_id'=>'069','parlimen_description'=>'PARIT','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>70, 'parlimen_id'=>'070','parlimen_description'=>'KAMPAR','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>71, 'parlimen_id'=>'071','parlimen_description'=>'GOPENG','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>72, 'parlimen_id'=>'072','parlimen_description'=>'TAPAH','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>73, 'parlimen_id'=>'073','parlimen_description'=>'PASIR SALAK','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>74, 'parlimen_id'=>'074','parlimen_description'=>'LUMUT','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>75, 'parlimen_id'=>'075','parlimen_description'=>'BAGAN DATUK','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>76, 'parlimen_id'=>'076','parlimen_description'=>'TELUK INTAN','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>77, 'parlimen_id'=>'077','parlimen_description'=>'TANJONG MALIM','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>78, 'parlimen_id'=>'078','parlimen_description'=>'CAMERON HIGHLANDS','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>79, 'parlimen_id'=>'079','parlimen_description'=>'LIPIS','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>80, 'parlimen_id'=>'080','parlimen_description'=>'RAUB','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>81, 'parlimen_id'=>'081','parlimen_description'=>'JERANTUT','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>82, 'parlimen_id'=>'082','parlimen_description'=>'INDERA MAHKOTA','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>83, 'parlimen_id'=>'083','parlimen_description'=>'KUANTAN','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>84, 'parlimen_id'=>'084','parlimen_description'=>'PAYA BESAR','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>85, 'parlimen_id'=>'085','parlimen_description'=>'PEKAN','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>86, 'parlimen_id'=>'086','parlimen_description'=>'MARAN','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>87, 'parlimen_id'=>'087','parlimen_description'=>'KUALA KRAU','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>88, 'parlimen_id'=>'088','parlimen_description'=>'TEMERLOH','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>89, 'parlimen_id'=>'089','parlimen_description'=>'BENTONG','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>90, 'parlimen_id'=>'090','parlimen_description'=>'BERA','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>91, 'parlimen_id'=>'091','parlimen_description'=>'ROMPIN','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>92, 'parlimen_id'=>'092','parlimen_description'=>'SABAK BERNAM','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>93, 'parlimen_id'=>'093','parlimen_description'=>'SUNGAI BESAR','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>94, 'parlimen_id'=>'094','parlimen_description'=>'HULU SELANGOR','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>95, 'parlimen_id'=>'095','parlimen_description'=>'TANJONG KARANG','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>96, 'parlimen_id'=>'096','parlimen_description'=>'KUALA SELANGOR','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>97, 'parlimen_id'=>'097','parlimen_description'=>'SELAYANG','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>98, 'parlimen_id'=>'098','parlimen_description'=>'GOMBAK','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>99, 'parlimen_id'=>'099','parlimen_description'=>'AMPANG','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>100, 'parlimen_id'=>'100','parlimen_description'=>'PANDAN','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>101, 'parlimen_id'=>'101','parlimen_description'=>'HULU LANGAT','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>102, 'parlimen_id'=>'102','parlimen_description'=>'BANGI','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>103, 'parlimen_id'=>'103','parlimen_description'=>'PUCHONG','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>104, 'parlimen_id'=>'104','parlimen_description'=>'SUBANG','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>105, 'parlimen_id'=>'105','parlimen_description'=>'PETALING JAYA','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>106, 'parlimen_id'=>'106','parlimen_description'=>'DAMANSARA','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>107, 'parlimen_id'=>'107','parlimen_description'=>'SUNGAI BULOH','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>108, 'parlimen_id'=>'108','parlimen_description'=>'SHAH ALAM','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>109, 'parlimen_id'=>'109','parlimen_description'=>'KAPAR','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>110, 'parlimen_id'=>'110','parlimen_description'=>'KLANG','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>111, 'parlimen_id'=>'111','parlimen_description'=>'KOTA RAJA','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>112, 'parlimen_id'=>'112','parlimen_description'=>'KUALA LANGAT','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>113, 'parlimen_id'=>'113','parlimen_description'=>'SEPANG','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>114, 'parlimen_id'=>'114','parlimen_description'=>'KEPONG','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>115, 'parlimen_id'=>'115','parlimen_description'=>'BATU','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>116, 'parlimen_id'=>'116','parlimen_description'=>'WANGSA MAJU','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>117, 'parlimen_id'=>'117','parlimen_description'=>'SEGAMBUT','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>118, 'parlimen_id'=>'118','parlimen_description'=>'SETIAWANGSA','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>119, 'parlimen_id'=>'119','parlimen_description'=>'TITIWANGSA','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>120, 'parlimen_id'=>'120','parlimen_description'=>'BUKIT BINTANG','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>121, 'parlimen_id'=>'121','parlimen_description'=>'LEMBAH PANTAI','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>122, 'parlimen_id'=>'122','parlimen_description'=>'SEPUTEH','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>123, 'parlimen_id'=>'123','parlimen_description'=>'CHERAS','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>124, 'parlimen_id'=>'124','parlimen_description'=>'BANDAR TUN RAZAK','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>125, 'parlimen_id'=>'125','parlimen_description'=>'PUTRAJAYA','state_id'=>'16','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>126, 'parlimen_id'=>'126','parlimen_description'=>'JELEBU','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>127, 'parlimen_id'=>'127','parlimen_description'=>'JEMPOL','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>128, 'parlimen_id'=>'128','parlimen_description'=>'SEREMBAN','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>129, 'parlimen_id'=>'129','parlimen_description'=>'KUALA PILAH','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>130, 'parlimen_id'=>'130','parlimen_description'=>'RASAH','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>131, 'parlimen_id'=>'131','parlimen_description'=>'REMBAU','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>132, 'parlimen_id'=>'132','parlimen_description'=>'PORT DICKSON','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>133, 'parlimen_id'=>'133','parlimen_description'=>'TAMPIN','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>134, 'parlimen_id'=>'134','parlimen_description'=>'MASJID TANAH','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>135, 'parlimen_id'=>'135','parlimen_description'=>'ALOR GAJAH','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>136, 'parlimen_id'=>'136','parlimen_description'=>'TANGGA BATU','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>137, 'parlimen_id'=>'137','parlimen_description'=>'HANG TUAH JAYA','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>138, 'parlimen_id'=>'138','parlimen_description'=>'KOTA MELAKA','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>139, 'parlimen_id'=>'139','parlimen_description'=>'JASIN','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>140, 'parlimen_id'=>'140','parlimen_description'=>'SEGAMAT','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>141, 'parlimen_id'=>'141','parlimen_description'=>'SEKIJANG','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>142, 'parlimen_id'=>'142','parlimen_description'=>'LABIS','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>143, 'parlimen_id'=>'143','parlimen_description'=>'PAGOH','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>144, 'parlimen_id'=>'144','parlimen_description'=>'LEDANG','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>145, 'parlimen_id'=>'145','parlimen_description'=>'BAKRI','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>146, 'parlimen_id'=>'146','parlimen_description'=>'MUAR','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>147, 'parlimen_id'=>'147','parlimen_description'=>'PARIT SULONG','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>148, 'parlimen_id'=>'148','parlimen_description'=>'AYER HITAM','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>149, 'parlimen_id'=>'149','parlimen_description'=>'SRI GADING','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>150, 'parlimen_id'=>'150','parlimen_description'=>'BATU PAHAT','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>151, 'parlimen_id'=>'151','parlimen_description'=>'SIMPANG RENGGAM','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>152, 'parlimen_id'=>'152','parlimen_description'=>'KLUANG','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>153, 'parlimen_id'=>'153','parlimen_description'=>'SEMBRONG','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>154, 'parlimen_id'=>'154','parlimen_description'=>'MERSING','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>155, 'parlimen_id'=>'155','parlimen_description'=>'TENGGARA','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>156, 'parlimen_id'=>'156','parlimen_description'=>'KOTA TINGGI','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>157, 'parlimen_id'=>'157','parlimen_description'=>'PENGERANG','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>158, 'parlimen_id'=>'158','parlimen_description'=>'TEBRAU','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>159, 'parlimen_id'=>'159','parlimen_description'=>'PASIR GUDANG','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>160, 'parlimen_id'=>'160','parlimen_description'=>'JOHOR BAHRU','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>161, 'parlimen_id'=>'161','parlimen_description'=>'PULAI','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>162, 'parlimen_id'=>'162','parlimen_description'=>'ISKANDAR PUTERI','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>163, 'parlimen_id'=>'163','parlimen_description'=>'KULAI','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>164, 'parlimen_id'=>'164','parlimen_description'=>'PONTIAN','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>165, 'parlimen_id'=>'165','parlimen_description'=>'TANJUNG PIAI','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>166, 'parlimen_id'=>'166','parlimen_description'=>'LABUAN','state_id'=>'15','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>167, 'parlimen_id'=>'167','parlimen_description'=>'KUDAT','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>168, 'parlimen_id'=>'168','parlimen_description'=>'KOTA MARUDU','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>169, 'parlimen_id'=>'169','parlimen_description'=>'KOTA BELUD','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>170, 'parlimen_id'=>'170','parlimen_description'=>'TUARAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>171, 'parlimen_id'=>'171','parlimen_description'=>'SEPANGGAR','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>172, 'parlimen_id'=>'172','parlimen_description'=>'KOTA KINABALU','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>173, 'parlimen_id'=>'173','parlimen_description'=>'PUTATAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>174, 'parlimen_id'=>'174','parlimen_description'=>'PENAMPANG','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>175, 'parlimen_id'=>'175','parlimen_description'=>'PAPAR','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>176, 'parlimen_id'=>'176','parlimen_description'=>'KIMANIS','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>177, 'parlimen_id'=>'177','parlimen_description'=>'BEAUFORT','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>178, 'parlimen_id'=>'178','parlimen_description'=>'SIPITANG','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>179, 'parlimen_id'=>'179','parlimen_description'=>'RANAU','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>180, 'parlimen_id'=>'180','parlimen_description'=>'KENINGAU','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>181, 'parlimen_id'=>'181','parlimen_description'=>'TENOM','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>182, 'parlimen_id'=>'182','parlimen_description'=>'PENSIANGAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>183, 'parlimen_id'=>'183','parlimen_description'=>'BELURAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>184, 'parlimen_id'=>'184','parlimen_description'=>'LIBARAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>185, 'parlimen_id'=>'185','parlimen_description'=>'BATU SAPI','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>186, 'parlimen_id'=>'186','parlimen_description'=>'SANDAKAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>187, 'parlimen_id'=>'187','parlimen_description'=>'KINABATANGAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>188, 'parlimen_id'=>'188','parlimen_description'=>'SILAM','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>189, 'parlimen_id'=>'189','parlimen_description'=>'SEMPORNA','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>190, 'parlimen_id'=>'190','parlimen_description'=>'TAWAU','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>191, 'parlimen_id'=>'191','parlimen_description'=>'KALABAKAN','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>192, 'parlimen_id'=>'192','parlimen_description'=>'MAS GADING','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>193, 'parlimen_id'=>'193','parlimen_description'=>'SANTUBONG','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>194, 'parlimen_id'=>'194','parlimen_description'=>'PETRA JAYA','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>195, 'parlimen_id'=>'195','parlimen_description'=>'BANDAR KUCHING','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>196, 'parlimen_id'=>'196','parlimen_description'=>'STAMPIN','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>197, 'parlimen_id'=>'197','parlimen_description'=>'KOTA SAMARAHAN','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>198, 'parlimen_id'=>'198','parlimen_description'=>'PUNCAK BORNEO','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>199, 'parlimen_id'=>'199','parlimen_description'=>'SERIAN','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>200, 'parlimen_id'=>'200','parlimen_description'=>'BATANG SADONG','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>201, 'parlimen_id'=>'201','parlimen_description'=>'BATANG LUPAR','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>202, 'parlimen_id'=>'202','parlimen_description'=>'SRI AMAN','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>203, 'parlimen_id'=>'203','parlimen_description'=>'LUBOK ANTU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>204, 'parlimen_id'=>'204','parlimen_description'=>'BETONG','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>205, 'parlimen_id'=>'205','parlimen_description'=>'SARATOK','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>206, 'parlimen_id'=>'206','parlimen_description'=>'TANJONG MANIS','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>207, 'parlimen_id'=>'207','parlimen_description'=>'IGAN','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>208, 'parlimen_id'=>'208','parlimen_description'=>'SARIKEI','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>209, 'parlimen_id'=>'209','parlimen_description'=>'JULAU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>210, 'parlimen_id'=>'210','parlimen_description'=>'KANOWIT','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>211, 'parlimen_id'=>'211','parlimen_description'=>'LANANG','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>212, 'parlimen_id'=>'212','parlimen_description'=>'SIBU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>213, 'parlimen_id'=>'213','parlimen_description'=>'MUKAH','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>214, 'parlimen_id'=>'214','parlimen_description'=>'SELANGAU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>215, 'parlimen_id'=>'215','parlimen_description'=>'KAPIT','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>216, 'parlimen_id'=>'216','parlimen_description'=>'HULU RAJANG','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>217, 'parlimen_id'=>'217','parlimen_description'=>'BINTULU','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>218, 'parlimen_id'=>'218','parlimen_description'=>'SIBUTI','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>219, 'parlimen_id'=>'219','parlimen_description'=>'MIRI','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>220, 'parlimen_id'=>'220','parlimen_description'=>'BARAM','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>221, 'parlimen_id'=>'221','parlimen_description'=>'LIMBANG','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>222, 'parlimen_id'=>'222','parlimen_description'=>'LAWAS','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],

            ]);

        }
    }
}
