<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RefPBT extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // check if table users is empty
        if(DB::table('ref__pbts')->get()->count() == 0){

            DB::table('ref__pbts')->insert([
                ['id'=>1, 'pbt_id'=>'201301','pbt_description'=>'Majlis Bandaraya Johor Bahru','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>2, 'pbt_id'=>'201302','pbt_description'=>'Majlis Perbandaran Johor Bahru Tengah','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>3, 'pbt_id'=>'201303','pbt_description'=>'Majlis Perbandaran Kulai','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>4, 'pbt_id'=>'201304','pbt_description'=>'Majlis Perbandaran Muar','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>5, 'pbt_id'=>'201305','pbt_description'=>'Majlis Daerah Tangkak','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>6, 'pbt_id'=>'201306','pbt_description'=>'Majlis Perbandaran Batu Pahat','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>7, 'pbt_id'=>'201307','pbt_description'=>'Majlis Daerah Yong Peng, Batu Pahat','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>8, 'pbt_id'=>'201308','pbt_description'=>'Majlis Daerah Segamat','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>9, 'pbt_id'=>'201309','pbt_description'=>'Majlis Daerah Labis, Segamat','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>10, 'pbt_id'=>'201310','pbt_description'=>'Majlis Perbandaran Kluang','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>11, 'pbt_id'=>'201311','pbt_description'=>'Majlis Daerah Simpang Renggam, Kluang','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>12, 'pbt_id'=>'201312','pbt_description'=>'Majlis Daerah Pontian','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>13, 'pbt_id'=>'201313','pbt_description'=>'Majlis Daerah Kota Tinggi','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>14, 'pbt_id'=>'201314','pbt_description'=>'Majlis Daerah Mersing','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>15, 'pbt_id'=>'201315','pbt_description'=>'Majlis Perbandaran Pasir Gudang','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>16, 'pbt_id'=>'201316','pbt_description'=>'Lembaga Bandaran Johor Tenggara','state_id'=>'01','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>17, 'pbt_id'=>'202301','pbt_description'=>'Majlis Bandaraya Alor Setar','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>18, 'pbt_id'=>'202302','pbt_description'=>'Majlis Perbandaran Sungai Petani','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>19, 'pbt_id'=>'202303','pbt_description'=>'Majlis Perbandaran Kulim','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>20, 'pbt_id'=>'202304','pbt_description'=>'Majlis Daerah Baling','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>21, 'pbt_id'=>'202305','pbt_description'=>'Majlis Daerah Kubang Pasu','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>22, 'pbt_id'=>'202306','pbt_description'=>'Majlis Daerah Yan','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>23, 'pbt_id'=>'202307','pbt_description'=>'Majlis Daerah Sik','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>24, 'pbt_id'=>'202308','pbt_description'=>'Majlis Daerah Pendang','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>25, 'pbt_id'=>'202309','pbt_description'=>'Majlis Daerah Padang Terap','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>26, 'pbt_id'=>'202310','pbt_description'=>'Majlis Perbandaran Langkawi','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>27, 'pbt_id'=>'202311','pbt_description'=>'Majlis Daerah Bandar Baharu','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>28, 'pbt_id'=>'202312','pbt_description'=>'PBT Taman Perindustrian Hi-Tech Kulim','state_id'=>'02','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>29, 'pbt_id'=>'203301','pbt_description'=>'Majlis Perbandaran Kota Bharu-Bandar Raya Islam','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>30, 'pbt_id'=>'203302','pbt_description'=>'Majlis Daerah Bachok','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>31, 'pbt_id'=>'203303','pbt_description'=>'Majlis Daerah Gua Musang','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>32, 'pbt_id'=>'203304','pbt_description'=>'Majlis Daerah Jeli','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>33, 'pbt_id'=>'203305','pbt_description'=>'Majlis Daerah Ketereh','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>34, 'pbt_id'=>'203306','pbt_description'=>'Majlis Daerah Dabong','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>35, 'pbt_id'=>'203307','pbt_description'=>'Majlis Daerah Kuala Krai','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>36, 'pbt_id'=>'203308','pbt_description'=>'Majlis Daerah Machang','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>37, 'pbt_id'=>'203309','pbt_description'=>'Majlis Daerah Pasir Mas','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>38, 'pbt_id'=>'203310','pbt_description'=>'Majlis Daerah Pasir Puteh','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>39, 'pbt_id'=>'203311','pbt_description'=>'Majlis Daerah Tanah Merah','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>40, 'pbt_id'=>'203312','pbt_description'=>'Majlis Daerah Tumpat','state_id'=>'03','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>41, 'pbt_id'=>'204301','pbt_description'=>'Majlis Perbandaran Melaka Bersejarah','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>42, 'pbt_id'=>'204302','pbt_description'=>'Majlis Perbandaran Alor Gajah','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>43, 'pbt_id'=>'204303','pbt_description'=>'Majlis Perbandaran Jasin','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>44, 'pbt_id'=>'204304','pbt_description'=>'Majlis Perbandaran Hang Tuah Jaya','state_id'=>'04','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>45, 'pbt_id'=>'205301','pbt_description'=>'Majlis Perbandaran Seremban','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>46, 'pbt_id'=>'205302','pbt_description'=>'Majlis Perbandaran Nilai','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>47, 'pbt_id'=>'205303','pbt_description'=>'Majlis Daerah Kuala Pilah','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>48, 'pbt_id'=>'205304','pbt_description'=>'Majlis Daerah Tampin','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>49, 'pbt_id'=>'205305','pbt_description'=>'Majlis Perbandaran Port Dickson','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>50, 'pbt_id'=>'205306','pbt_description'=>'Majlis Daerah Jelebu','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>51, 'pbt_id'=>'205307','pbt_description'=>'Majlis Daerah Rembau','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>52, 'pbt_id'=>'205308','pbt_description'=>'Majlis Daerah Jempol','state_id'=>'05','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>53, 'pbt_id'=>'206301','pbt_description'=>'Majlis Perbandaran Kuantan','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>54, 'pbt_id'=>'206302','pbt_description'=>'Majlis Perbandaran Temerloh','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>55, 'pbt_id'=>'206303','pbt_description'=>'Majlis Perbandaran Bentong','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>56, 'pbt_id'=>'206304','pbt_description'=>'Majlis Daerah Pekan','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>57, 'pbt_id'=>'206305','pbt_description'=>'Majlis Daerah Lipis','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>58, 'pbt_id'=>'206306','pbt_description'=>'Majlis Daerah Cameron Highlands','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>59, 'pbt_id'=>'206307','pbt_description'=>'Majlis Daerah Raub','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>60, 'pbt_id'=>'206308','pbt_description'=>'Majlis Daerah Bera','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>61, 'pbt_id'=>'206309','pbt_description'=>'Majlis Daerah Maran','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>62, 'pbt_id'=>'206310','pbt_description'=>'Majlis Daerah Rompin','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>63, 'pbt_id'=>'206311','pbt_description'=>'Majlis Daerah Jerantut','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>64, 'pbt_id'=>'206312','pbt_description'=>'Lembaga Pembangunan Tioman','state_id'=>'06','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>65, 'pbt_id'=>'207301','pbt_description'=>'Majlis Perbandaran Pulau Pinang','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>66, 'pbt_id'=>'207302','pbt_description'=>'Majlis Perbandaran Seberang Perai','state_id'=>'07','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>67, 'pbt_id'=>'208301','pbt_description'=>'Majlis Bandaraya Ipoh','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>68, 'pbt_id'=>'208302','pbt_description'=>'Majlis Perbandaran Taiping','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>69, 'pbt_id'=>'208303','pbt_description'=>'Majlis Perbandaran Manjung','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>70, 'pbt_id'=>'208304','pbt_description'=>'Majlis Daerah Perak Tengah, Seri Iskandar','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>71, 'pbt_id'=>'208305','pbt_description'=>'Majlis Perbandaran Kuala Kangsar','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>72, 'pbt_id'=>'208306','pbt_description'=>'Majlis Daerah Selama','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>73, 'pbt_id'=>'208307','pbt_description'=>'Majlis Daerah Batu Gajah','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>74, 'pbt_id'=>'208308','pbt_description'=>'Majlis Daerah Kampar','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>75, 'pbt_id'=>'208309','pbt_description'=>'Majlis Daerah Gerik','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>76, 'pbt_id'=>'208310','pbt_description'=>'Majlis Daerah Lenggong','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>77, 'pbt_id'=>'208311','pbt_description'=>'Majlis Daerah Pengkalan Hulu','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>78, 'pbt_id'=>'208312','pbt_description'=>'Majlis Daerah Tapah','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>79, 'pbt_id'=>'208313','pbt_description'=>'Majlis Daerah Tanjong Malim','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>80, 'pbt_id'=>'208314','pbt_description'=>'Majlis Perbandaran Teluk Intan','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>81, 'pbt_id'=>'208315','pbt_description'=>'Majlis Daerah Kerian','state_id'=>'08','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>82, 'pbt_id'=>'209301','pbt_description'=>'Majlis Perbandaran Kangar','state_id'=>'09','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>83, 'pbt_id'=>'210301','pbt_description'=>'Majlis Bandaraya Shah Alam','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>84, 'pbt_id'=>'210302','pbt_description'=>'Majlis Bandaraya Petaling Jaya','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>85, 'pbt_id'=>'210303','pbt_description'=>'Majlis Perbandaran Klang','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>86, 'pbt_id'=>'210304','pbt_description'=>'Majlis Perbandaran Ampang Jaya','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>87, 'pbt_id'=>'210305','pbt_description'=>'Majlis Perbandaran Subang Jaya','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>88, 'pbt_id'=>'210306','pbt_description'=>'Majlis Perbandaran Selayang','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>89, 'pbt_id'=>'210307','pbt_description'=>'Majlis Perbandaran Kajang','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>90, 'pbt_id'=>'210308','pbt_description'=>'Majlis Daerah Kuala Selangor','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>91, 'pbt_id'=>'210309','pbt_description'=>'Majlis Daerah Kuala Langat','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>92, 'pbt_id'=>'210310','pbt_description'=>'Majlis Daerah Hulu Selangor','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>93, 'pbt_id'=>'210311','pbt_description'=>'Majlis Daerah Sabak Bernam','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>94, 'pbt_id'=>'210313','pbt_description'=>'Majlis Perbandaran Sepang','state_id'=>'10','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>95, 'pbt_id'=>'211301','pbt_description'=>'Majlis Bandaraya Kuala Terengganu','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>96, 'pbt_id'=>'211302','pbt_description'=>'Majlis Daerah Besut','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>97, 'pbt_id'=>'211303','pbt_description'=>'Majlis Daerah Setiu','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>98, 'pbt_id'=>'211304','pbt_description'=>'Majlis Perbandaran Dungun','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>99, 'pbt_id'=>'211305','pbt_description'=>'Majlis Daerah Hulu Terengganu','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>100, 'pbt_id'=>'211306','pbt_description'=>'Majlis Perbandaran Kemaman','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>101, 'pbt_id'=>'211307','pbt_description'=>'Majlis Daerah Marang','state_id'=>'11','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>102, 'pbt_id'=>'361301','pbt_description'=>'Dewan Bandaraya Kota Kinabalu','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>103, 'pbt_id'=>'366301','pbt_description'=>'Majlis Perbandaran Sandakan','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>104, 'pbt_id'=>'366302','pbt_description'=>'Majlis Perbandaran Tawau','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>105, 'pbt_id'=>'366303','pbt_description'=>'Lembaga Bandaran Kudat','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>106, 'pbt_id'=>'366304','pbt_description'=>'Majlis Daerah Beaufort','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>107, 'pbt_id'=>'366305','pbt_description'=>'Majlis Daerah Beluran','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>108, 'pbt_id'=>'366306','pbt_description'=>'Majlis Daerah Keningau','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>109, 'pbt_id'=>'366307','pbt_description'=>'Majlis Daerah Kinabatangan','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>110, 'pbt_id'=>'366308','pbt_description'=>'Majlis Daerah Kota Belud','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>111, 'pbt_id'=>'366309','pbt_description'=>'Majlis Daerah Kota Marudu','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>112, 'pbt_id'=>'366310','pbt_description'=>'Majlis Daerah Kuala Penyu','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>113, 'pbt_id'=>'366311','pbt_description'=>'Majlis Daerah Kunak','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>114, 'pbt_id'=>'366312','pbt_description'=>'Majlis Daerah Lahad Datu','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>115, 'pbt_id'=>'366313','pbt_description'=>'Majlis Daerah Nabawan','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>116, 'pbt_id'=>'366314','pbt_description'=>'Majlis Daerah Papar','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>117, 'pbt_id'=>'366315','pbt_description'=>'Majlis Daerah Penampang','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>118, 'pbt_id'=>'366316','pbt_description'=>'Majlis Daerah Ranau','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>119, 'pbt_id'=>'366317','pbt_description'=>'Majlis Daerah Semporna','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>120, 'pbt_id'=>'366318','pbt_description'=>'Majlis Daerah Sipitang','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>121, 'pbt_id'=>'366319','pbt_description'=>'Majlis Daerah Tambunan','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>122, 'pbt_id'=>'366320','pbt_description'=>'Majlis Daerah Tenom','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>123, 'pbt_id'=>'366321','pbt_description'=>'Majlis Daerah Tuaran','state_id'=>'12','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>124, 'pbt_id'=>'481501','pbt_description'=>'Lembaga Kemjuan Bintulu Sarawak','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>125, 'pbt_id'=>'481503','pbt_description'=>'Dewan Bandaraya Kuching Utara','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>126, 'pbt_id'=>'487301','pbt_description'=>'Majlis Bandaraya Kuching Selatan','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>127, 'pbt_id'=>'487302','pbt_description'=>'Majlis Perbandaran Padawan','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>128, 'pbt_id'=>'487303','pbt_description'=>'Majlis Perbandaran Sibu','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>129, 'pbt_id'=>'487304','pbt_description'=>'Majlis Bandaraya Miri','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>130, 'pbt_id'=>'487305','pbt_description'=>'Majlis Daerah Bau','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>131, 'pbt_id'=>'487306','pbt_description'=>'Majlis Daerah Betong','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>132, 'pbt_id'=>'487307','pbt_description'=>'Majlis Daerah Dalat dan Mukah','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>133, 'pbt_id'=>'487308','pbt_description'=>'Majlis Daerah Kanowit','state_id'=>'13','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>134, 'pbt_id'=>'148301','pbt_description'=>'Dewan Bandaraya Kuala Lumpur','state_id'=>'14','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>135, 'pbt_id'=>'148401','pbt_description'=>'Perbadanan Labuan','state_id'=>'15','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
                ['id'=>136, 'pbt_id'=>'148402','pbt_description'=>'Perbadanan Putrajaya','state_id'=>'16','status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],

            ]);

        }
    }
}
